#!/usr/bin/env python3
# Makes the signed test files of the Content Credentials tests, in
# images/generated/, from the downloaded ones (fetch-images.py first), with
# the C2PA library of the plug-in (plug-ins/content-credentials/vendor) and
# the test certificate of c2pa-rs (which is on no trust list):
#
#   ai-generated.<ext>   a "generated by AI" claim (c2pa.created,
#                        trainedAlgorithmicMedia), in each format the
#                        library can sign: png webp avif heic heif jxl tif gif jpg
#   ai-edited.jpg        a photo (no credentials) opened, ai-generated.png
#                        placed into it, and edited with generative AI
#                        (compositeWithTrainedAlgorithmicMedia): ingredients
#                        with and without credentials
#   tampered-pixels.png  ai-generated.png with some pixels changed after
#                        signing (a valid PNG: the CRC is recomputed)
#   xmp-ai.jpg, .png     no C2PA; only XMP with the IPTC digital source type
#                        trainedAlgorithmicMedia (as some AI services write)
#
# Signing is offline (no time stamp authority), so "signed at" is empty.
#
# Copyright 2026 David
# SPDX-License-Identifier: GPL-3.0-or-later
import os
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.dirname(os.path.dirname(HERE))
IMAGES = os.path.join(HERE, 'images')
OUT = os.path.join(IMAGES, 'generated')
sys.path.insert(0, os.path.join(SRC, 'plug-ins', 'content-credentials'))
import c2pa_report  # noqa: E402

IPTC = 'http://cv.iptc.org/newscodes/digitalsourcetype/'
GENERATOR = [{'name': 'gimp-forensics test fixtures', 'version': '1'}]
BASES = {
    'png': 'c2pa-rs-sample1.png', 'webp': 'c2pa-rs-sample1.webp',
    'avif': 'c2pa-rs-sample1.avif', 'heic': 'c2pa-rs-sample1.heic', 'heif': 'c2pa-rs-sample1.heif',
    'jxl': 'c2pa-rs-sample1.jxl', 'tif': 'c2pa-rs-test.tiff', 'gif': 'c2pa-rs-sample1.gif',
    'jpg': 'adobe-20220124-A.jpg',
}
MIME = {'png': 'image/png', 'webp': 'image/webp', 'avif': 'image/avif', 'heic': 'image/heic', 'heif': 'image/heif',
        'jxl': 'image/jxl', 'tif': 'image/tiff', 'gif': 'image/gif', 'jpg': 'image/jpeg'}

XMP_AI = ('<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF '
          'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description '
          'rdf:about="" xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" '
          'xmlns:xmp="http://ns.adobe.com/xap/1.0/" '
          'Iptc4xmpExt:DigitalSourceType="' + IPTC + 'trainedAlgorithmicMedia" '
          'xmp:CreatorTool="Example Image Generator 1.0"/></rdf:RDF></x:xmpmeta>')


def signer(c2pa):
    with open(os.path.join(IMAGES, 'c2pa-rs-es256.pem'), 'rb') as f:
        key = f.read()
    with open(os.path.join(IMAGES, 'c2pa-rs-es256.pub'), 'rb') as f:
        cert = f.read()
    return c2pa.Signer.from_info(c2pa.C2paSignerInfo(b'es256', cert, key, None))


def context(c2pa):
    s = c2pa_report.settings([])
    s['builder'] = {'thumbnail': {'enabled': False}}
    return c2pa.Context.from_dict(s)


def sign(c2pa, manifest, src, dst, ingredients=()):
    b = c2pa.Builder(manifest, context=context(c2pa))
    for spec, path, mime in ingredients:
        with open(path, 'rb') as f:
            b.add_ingredient(spec, mime, f)
    if os.path.exists(dst):
        os.remove(dst)
    # (with the MIME type given: the Python of the Flatpak does not know
    # every extension)
    mime = MIME[os.path.splitext(dst)[1][1:]]
    with open(src, 'rb') as source, open(dst, 'w+b') as dest:
        b.sign(signer(c2pa), mime, source, dest)


def generated(title):
    return {
        'claim_generator_info': GENERATOR,
        'title': title,
        'assertions': [{'label': 'c2pa.actions.v2', 'data': {'actions': [{
            'action': 'c2pa.created',
            'softwareAgent': {'name': 'Example Image Generator', 'version': '1.0'},
            'digitalSourceType': IPTC + 'trainedAlgorithmicMedia',
            'description': 'Made from a text prompt'}]}}],
    }


def png_chunks(data):
    i = 8
    while i < len(data):
        length, ctype = struct.unpack('>I4s', data[i:i + 8])
        yield i, length, ctype
        i += 12 + length


def tamper_png(src, dst):
    """Changes some pixels of a PNG and recomputes the chunk's CRC, so the
    file stays valid and only the C2PA data hash can tell."""
    data = bytearray(open(src, 'rb').read())
    idat = b''
    first = None
    for i, length, ctype in png_chunks(data):
        if ctype == b'IDAT':
            first = first if first is not None else i
            idat += bytes(data[i + 8:i + 8 + length])
    raw = bytearray(zlib.decompress(idat))
    # the first bytes of a row in the middle (the filter byte is left)
    mid = len(raw) // 2
    for k in range(1, 400):
        raw[mid + k] ^= 0x5a
    new_idat = zlib.compress(bytes(raw), 9)
    out = bytearray(data[:first])
    out += struct.pack('>I', len(new_idat)) + b'IDAT' + new_idat
    out += struct.pack('>I', zlib.crc32(b'IDAT' + new_idat) & 0xffffffff)
    for i, length, ctype in png_chunks(data):
        if i > first and ctype != b'IDAT':
            out += data[i:i + 12 + length]
    open(dst, 'wb').write(bytes(out))


def xmp_jpeg(src, dst):
    """The JPEG with its XMP (APP1) replaced by XMP_AI."""
    data = open(src, 'rb').read()
    head = b'http://ns.adobe.com/xap/1.0/\x00'
    payload = head + XMP_AI.encode()
    out = bytearray(b'\xff\xd8')
    out += b'\xff\xe1' + struct.pack('>H', len(payload) + 2) + payload
    for marker, pos, length in c2pa_report._jpeg_segments(data):
        if marker == 0xe1 and data[pos:pos + len(head)] == head:
            continue
        if marker == 0xda:
            out += data[pos - 4:]
            break
        out += data[pos - 4:pos + length]
    open(dst, 'wb').write(bytes(out))


def xmp_png(src, dst):
    """The PNG with an iTXt XML:com.adobe.xmp chunk after IHDR."""
    data = open(src, 'rb').read()
    body = b'XML:com.adobe.xmp\x00\x00\x00\x00\x00' + XMP_AI.encode()
    chunk = struct.pack('>I', len(body)) + b'iTXt' + body + \
        struct.pack('>I', zlib.crc32(b'iTXt' + body) & 0xffffffff)
    out = bytearray(data[:8])
    for i, length, ctype in png_chunks(data):
        if ctype == b'caBX':
            continue
        out += data[i:i + 12 + length]
        if ctype == b'IHDR':
            out += chunk
    open(dst, 'wb').write(bytes(out))


def main():
    c2pa = c2pa_report.load_c2pa()
    if c2pa is None:
        sys.exit('make-fixtures.py: no C2PA library (%s); run '
                 'plug-ins/content-credentials/fetch-deps.py' % c2pa_report.library_error())
    os.makedirs(OUT, exist_ok=True)
    made = []
    for ext, base in BASES.items():
        dst = os.path.join(OUT, 'ai-generated.' + ext)
        sign(c2pa, generated('ai-generated.' + ext), os.path.join(IMAGES, base), dst)
        made.append(dst)
    photo = os.path.join(IMAGES, 'adobe-20220124-A.jpg')
    dst = os.path.join(OUT, 'ai-edited.jpg')
    sign(c2pa, {
        'claim_generator_info': GENERATOR,
        'title': 'ai-edited.jpg',
        'assertions': [{'label': 'c2pa.actions.v2', 'data': {'actions': [
            {'action': 'c2pa.opened', 'softwareAgent': {'name': 'Example Editor', 'version': '2'},
             'parameters': {'ingredientIds': ['photo']}},
            {'action': 'c2pa.placed', 'softwareAgent': {'name': 'Example Editor', 'version': '2'},
             'parameters': {'ingredientIds': ['generated']}},
            {'action': 'c2pa.edited', 'softwareAgent': {'name': 'Example Generative Fill',
                                                        'version': '3'},
             'digitalSourceType': IPTC + 'compositeWithTrainedAlgorithmicMedia',
             'description': 'Generative fill'},
        ]}}],
    }, photo, dst, ingredients=[
        ({'title': 'photo.jpg', 'relationship': 'parentOf', 'label': 'photo'}, photo,
         'image/jpeg'),
        ({'title': 'ai-generated.png', 'relationship': 'componentOf', 'label': 'generated'},
         os.path.join(OUT, 'ai-generated.png'), 'image/png'),
    ])
    made.append(dst)
    dst = os.path.join(OUT, 'tampered-pixels.png')
    tamper_png(os.path.join(OUT, 'ai-generated.png'), dst)
    made.append(dst)
    dst = os.path.join(OUT, 'xmp-ai.jpg')
    xmp_jpeg(photo, dst)
    made.append(dst)
    dst = os.path.join(OUT, 'xmp-ai.png')
    xmp_png(os.path.join(IMAGES, 'c2pa-rs-sample1.png'), dst)
    made.append(dst)
    for m in made:
        print('made', os.path.relpath(m, HERE))


if __name__ == '__main__':
    main()
